# LaTeX2HTML 95 (Thu Jan 19 1995)
# Associate image original text (scrambled) with physical files.

$key = q/{_inline}$c_iinU(R)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img536.gif">'; 
$key = q/{_inline}$stnotinP${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img291.gif">'; 
$key = q/{_inline}$Ineq0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img89.gif">'; 
$key = q/{_inline}$f_i_j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img604.gif">'; 
$key = q/{_inline}$ainR${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img67.gif">'; 
$key = q/{_inline}$f_1,ldots,f_l,g_1,ldots,g_n${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img523.gif">'; 
$key = q/{_inline}$f(x)=a_ix^i+cdots+a_1x+a_0inI${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img596.gif">'; 
$key = q/{displaymath}p_1cdotsp_rq_1cdotsq_s=pv_1cdotsv_t{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img355.gif">'; 
$key = q/{_inline}$N_0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img582.gif">'; 
$key = q/{_inline}$rinR${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img74.gif">'; 
$key = q/{_inline}$f_0(x)g_0(x)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img474.gif">'; 
$key = q/{_inline}$IneqR${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img63.gif">'; 
$key = q/{_inline}$f(x)=I(f)f_0(x)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img469.gif">'; 
$key = q/{_inline}$degg=-infty${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img26.gif">'; 
$key = q/{_inline}$R^#${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img7.gif">'; 
$key = q/{_inline}$f(x)=cf_0(x)=c'f'_0(x)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img438.gif">'; 
$key = q/{_inline}$1inR=Ra${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img84.gif">'; 
$key = q/{_inline}$S^-1R${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img253.gif">'; 
$key = q/{_inline}$M_isubsetM_i+1,;M_ineqM_i+1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img575.gif">'; 
$key = q/{_inline}$binI${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img141.gif">'; 
$key = q/{_inline}$cmidd${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img415.gif">'; 
$key = q/{_inline}$dmida_i${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img411.gif">'; 
$key = q/{_inline}$(modI_1)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img222.gif">'; 
$key = q/{_inline}$c_i${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img194.gif">'; 
$key = q/{_inline}$I=(a)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img138.gif">'; 
$key = q/{_inline}$m=a_ic_i${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img431.gif">'; 
$key = q/{_inline}$f=a_mx^m+cdots+a_1x+a_0inI${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img607.gif">'; 
$key = q/{_inline}$degg(x);SPM_gt;1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img172.gif">'; 
$key = q/{_inline}$0neqf(x)inR[x]${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img506.gif">'; 
$key = q/{displaymath}a_i=b_0c_i+b_1c_i-1+cdots+b_ic_0equivb_0c_inotequiv0;(modp).{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img196.gif">'; 
$key = q/{_inline}$(at+bs)stinP'${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img292.gif">'; 
$key = q/{_inline}$anotinP${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img313.gif">'; 
$key = q/{_inline}$a'${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img443.gif">'; 
$key = q/{_inline}$a_1,ldots,a_ninR${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img410.gif">'; 
$key = q/{_inline}$c_if_i=g_i${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img531.gif">'; 
$key = q/{_inline}$pneq0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img335.gif">'; 
$key = q/{_inline}$f(x)=(b_0a_0)+(b_1a_1)x+cdots+(b_na_n)x^n${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img428.gif">'; 
$key = q/{_inline}$a_imidm${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img419.gif">'; 
$key = q/{_inline}$q=q_1+(a_nb_m^-1)x^n-m${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img41.gif">'; 
$key = q/{_inline}$asinP'LeftrightarrowanotinP${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img297.gif">'; 
$key = q/{_inline}$a_i_j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img605.gif">'; 
$key = q/{_inline}$R_i^*={(0,ldots,0,a,0,ldots,0)midainR_i}${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img208.gif">'; 
$key = q/{_inline}$A+B={a+bmidainA,binB}${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img60.gif">'; 
$key = q/{_inline}$c_1inI_1,;c_2inI_2${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img220.gif">'; 
$key = q/{_inline}$bigcup_i=1^infty(a_i)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img387.gif">'; 
$key = q/{_inline}$i_0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img464.gif">'; 
$key = q/{_inline}$xin(m),;yin(n)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img215.gif">'; 
$key = q/{_inline}$vinU(R)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img337.gif">'; 
$key = q/{_inline}$IysubsetI${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img58.gif">'; 
$key = q/{_inline}$f_0'(x)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img447.gif">'; 
$key = q/{_inline}$q,rinR${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img95.gif">'; 
$key = q/{_inline}$1notinP${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img317.gif">'; 
$key = q/{_inline}$M=R-U(R)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img279.gif">'; 
$key = q/{displaymath}(f(x))subset(g(x))subsetK[x]{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img174.gif">'; 
$key = q/{displaymath}a=bc=bad=abdrightarrowa(bd-1)=0{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img145.gif">'; 
$key = q/{_inline}$degh_0=degh=0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img491.gif">'; 
$key = q/{_inline}$I(f)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img519.gif">'; 
$key = q/{_inline}$a=p_1a_1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img377.gif">'; 
$key = q/{_inline}$N=bigcup_iM_i${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img587.gif">'; 
$key = q/{_inline}$(m)subset(n)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img154.gif">'; 
$key = q/{_inline}$(0)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img132.gif">'; 
$key = q/{_inline}$McapU(R)=emptyset${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img273.gif">'; 
$key = q/{_inline}$a'b=ab'u${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img448.gif">'; 
$key = q/{_inline}$degg;SPM_gt;0,degh;SPM_gt;0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img512.gif">'; 
$key = q/{_inline}$R[x]${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img510.gif">'; 
$key = q/{_inline}$c,c'${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img451.gif">'; 
$key = q/{_inline}$I_2cdotsI_nsubsetI_j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img241.gif">'; 
$key = q/{_inline}$Leftrightarrow${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img130.gif">'; 
$key = q/{_inline}$I(f)inU(R)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img502.gif">'; 
$key = q/{_inline}$U(R)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img3.gif">'; 
$key = q/{_inline}$p=uvtouinU(R)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img336.gif">'; 
$key = q/{_inline}$uf_1cdotsf_l=g_1cdotsg_n${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img530.gif">'; 
$key = q/{displaymath}f=f(x)=a_0+a_1x+cdots+a_nx^n,;g=g(x)=b_0+b_1x+cdots+b_mx^m{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img15.gif">'; 
$key = q/{_inline}$a_i${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img385.gif">'; 
$key = q/{_inline}$x_1equiv0;(modI_j)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img242.gif">'; 
$key = q/{_inline}$as't=a'stinP${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img308.gif">'; 
$key = q/{displaymath}(a)subset(a_1)subset(a_2)subsetcdotssubset(a_i)subsetcdots{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img386.gif">'; 
$key = q/{_inline}$abin(p)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img350.gif">'; 
$key = q/{_inline}$M_n=M_n+1=cdots${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img572.gif">'; 
$key = q/{_inline}$f=a_0inI_0=sum_j=1^s_0Ra_0_j=sum_j=1^s_0Rf_0_j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img609.gif">'; 
$key = q/{displaymath}xequiva_1c_2+a_2c_1equiva_1c_2equiva_1(1-c_1)equiva_1-a_1c_1equiva_1{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img223.gif">'; 
$key = q/{_inline}$h=f-(a_nb_m^-1)x^n-mg${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img34.gif">'; 
$key = q/{_inline}$0_S^-1R=01${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img257.gif">'; 
$key = q/{_inline}$(1)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img475.gif">'; 
$key = q/{_inline}$ginG${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img551.gif">'; 
$key = q/{_inline}$finR${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img498.gif">'; 
$key = q/{displaymath}I=sum_i=0^rsum_j=1^s_iR[x]f_i_j(x).{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img606.gif">'; 
$key = q/{_inline}$f(x)inR[x]${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img488.gif">'; 
$key = q/{_inline}$f(x)=I(g)I(h)g_0(x)h_0(x)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img487.gif">'; 
$key = q/{_inline}$as=a's'Leftrightarrowas'-a's=0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img262.gif">'; 
$key = q/{_inline}$U(K[x])=U(K)=K^*${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img175.gif">'; 
$key = q/{ex}部分環は、環である。{ex}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img102.gif">'; 
$key = q/{_inline}$xyin(x+I)(y+I)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img55.gif">'; 
$key = q/{_inline}$c=dm${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img436.gif">'; 
$key = q/{_inline}$1_S^-1R=11${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img258.gif">'; 
$key = q/{_inline}$up_1cdotsp_k=q_1cdotsq_m${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img528.gif">'; 
$key = q/{_inline}$a=p_1cdotsp_r${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img352.gif">'; 
$key = q/{_inline}$(n)=(m)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img155.gif">'; 
$key = q/{_inline}$M_m${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img589.gif">'; 
$key = q/{_inline}$(q_i)subset(p_1)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img399.gif">'; 
$key = q/{_inline}$M_i${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img574.gif">'; 
$key = q/{_inline}$as=a's'${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img303.gif">'; 
$key = q/{_inline}$din(a_i)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img389.gif">'; 
$key = q/{_inline}$0={0}${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img69.gif">'; 
$key = q/{_inline}$degg;SPM_lt;degf${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img513.gif">'; 
$key = q/{displaymath}deg(f(x)-x^esum_j=1^s_m-ec_jf_(m-e)_j(x));SPM_lt;degf(x){displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img613.gif">'; 
$key = q/{_inline}$bZ[x]${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img406.gif">'; 
$key = q/{displaymath}-infty=degfg=degf+degg.{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img24.gif">'; 
$key = q/{_inline}$s1inU(S^-1R)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img261.gif">'; 
$key = q/{_inline}$binR${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img322.gif">'; 
$key = q/{_inline}$(2)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img468.gif">'; 
$key = q/{_inline}${s_1,ldots,s_n}${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img619.gif">'; 
$key = q/{_inline}$u_1,u_2,ldots,u_n${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img590.gif">'; 
$key = q/{_inline}$rho(r);SPM_lt;rho(a)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img94.gif">'; 
$key = q/{_inline}$g=b_mx^m+cdots+b_1x+b_0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img30.gif">'; 
$key = q/{_inline}$ain(a)=IsubsetJ=(b)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img136.gif">'; 
$key = q/{_inline}$f=I(f)f_0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img515.gif">'; 
$key = q/{_inline}$kerfneqM${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img561.gif">'; 
$key = q/{_inline}$I_0subsetI_1subsetI_2subsetcdots${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img598.gif">'; 
$key = q/{_inline}$ainRasubsetM${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img277.gif">'; 
$key = q/{_inline}$fneq0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img560.gif">'; 
$key = q/{displaymath}h(x)=f(x)g(x)=c_0+c_1x+cdots+a_nx^n,;pmidc_i,;i=0,1,ldots,n{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img462.gif">'; 
$key = q/{_inline}$sinS${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img260.gif">'; 
$key = q/{_inline}$binU(R)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img351.gif">'; 
$key = q/{_inline}$cinI${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img140.gif">'; 
$key = q/{_inline}$(a)=(b)Leftrightarrowa=bu${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img332.gif">'; 
$key = q/{_inline}$imf${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img558.gif">'; 
$key = q/{_inline}$I=R-U(R)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img282.gif">'; 
$key = q/{_inline}$h=gq_1+r${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img39.gif">'; 
$key = q/{_inline}$(a)subset(p_1)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img376.gif">'; 
$key = q/{displaymath}1=prod_j=2^n(c_1^(j)+c_j)equivc_2cdotsc_n;(modI_1){displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img232.gif">'; 
$key = q/{_inline}$(3)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img125.gif">'; 
$key = q/{_inline}$degr;SPM_lt;degg${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img38.gif">'; 
$key = q/{_inline}$RsubsetI${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img76.gif">'; 
$key = q/{_inline}$f(x)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img169.gif">'; 
$key = q/{_inline}$q-q'=0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img46.gif">'; 
$key = q/{_inline}$RneqJ${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img281.gif">'; 
$key = q/{eg}_inline$Ainmat_n(bC)$_inline、_inline$psi:bC[x]tomat_n(bC);(f(x)mapstof(A))$_inlineとする。Hamilton-Cayleyの定理により、_inline$kerpsisupset(det(xI-A))neq0$_inline。よって、monicな多項式によって、_inline$kerpsi=p_A(x)$_inlineと書ける。この_inline$p_A(x)$_inlineを最小多項式という。上の事から_inline$p_Amiddet(xI-A)$_inlineである。例えば、displaymathA=left(arraycc1;SPM_amp;00;SPM_amp;-2arrayright),;B=left(arraycc0;SPM_amp;1-4;SPM_amp;4arrayright),;C=left(arraycc2;SPM_amp;00;SPM_amp;2arrayright)displaymathとしたとき、それぞれの最小多項式は、displaymathp_A(x)=(x-1)(x+2),;p_B(x)=(x-2)^2,;p_C(x)=x-2displaymathである。{eg}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img114.gif">'; 
$key = q/{_inline}$a_n=b_rc_s${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img191.gif">'; 
$key = q/{_inline}$a=p_1p_2cdots(p_ra_r)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img393.gif">'; 
$key = q/{_inline}$(1)Rightarrow(2)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img271.gif">'; 
$key = q/{_inline}$f_0(x)=e_0+e_1x+cdots+e_nx^n${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img437.gif">'; 
$key = q/{_inline}$x=a_1x_1+cdots+a_nx_n${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img244.gif">'; 
$key = q/{_inline}$p_2cdotsp_r=uq_2cdotsq_s${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img404.gif">'; 
$key = q/{_inline}$xIsubsetI${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img57.gif">'; 
$key = q/{_inline}$Rightarrow${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img128.gif">'; 
$key = q/{_inline}$(i=0,1,ldots,r)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img603.gif">'; 
$key = q/{_inline}$s_1,ldots,s_ninS${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img617.gif">'; 
$key = q/{displaymath}p_1p_2cdotsp_r=p_1uq_2cdotsq_s{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img403.gif">'; 
$key = q/{_inline}$de_i=b_ic_i${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img433.gif">'; 
$key = q/{displaymath}g(x)=b_rx^r+cdots+b_0,;h(x)=c_sx^s+cdots+c_0{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img186.gif">'; 
$key = q/{_inline}$lmidm${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img421.gif">'; 
$key = q/{_inline}$AB={sum_ia_ib_imida_iinA,;binB}${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img61.gif">'; 
$key = q/{displaymath}a_minI_m=I_m-e=sum_j=1^s_m-eRa_(m-e)_j{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img611.gif">'; 
$key = q/{_inline}$NsubsetM${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img538.gif">'; 
$key = q/{_inline}$J=(b)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img135.gif">'; 
$key = q/{_inline}$papproxq_j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img357.gif">'; 
$key = q/{_inline}$degf=deg0=-infty${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img22.gif">'; 
$key = q/{_inline}$(a_1s_1)(a_2s_2)=(a_1a_2s_1s_2)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img255.gif">'; 
$key = q/{_inline}$U(R_P)capP'=emptyset${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img326.gif">'; 
$key = q/{_inline}$xinN${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img541.gif">'; 
$key = q/{_inline}$b_j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img465.gif">'; 
$key = q/{displaymath}f(a)=f(b)Leftrightarrowf(a-b)=0Leftrightarrowa-binkerfLeftrightarrowa+kerf=b+kerf{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img111.gif">'; 
$key = q/{_inline}$(i)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img509.gif">'; 
$key = q/{_inline}$tnotinP${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img323.gif">'; 
$key = q/{_inline}$P'${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img295.gif">'; 
$key = q/{_inline}$imf=N${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img564.gif">'; 
$key = q/{_inline}$aneq0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img82.gif">'; 
$key = q/{_inline}$phi(g):VtoV,;(vmapstogv)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img552.gif">'; 
$key = q/{eg}enumerateitem_inline$R$_inlineの非零因子全体（零因子以外の元すべて）は、乗法的部分集合である。item_inline$P$_inlineを_inline$R$_inlineの素イデアルとしたとき、_inline$R-P$_inlineは、乗法的部分集合である。enumerate{eg}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img247.gif">'; 
$key = q/{_inline}$barf${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img110.gif">'; 
$key = q/{_inline}$(as)+(bt)=(at+bs)st${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img288.gif">'; 
$key = q/{_inline}$sainR_P${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img314.gif">'; 
$key = q/{_inline}$f(x)inK[x]${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img455.gif">'; 
$key = q/{_inline}$0=0x+(-0x)=(0+0)x+(-0x)=0x+0x+(-0x)=0x+0=0x${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img8.gif">'; 
$key = q/{_inline}$rleqs${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img395.gif">'; 
$key = q/{_inline}$p_1,ldots,p_k,q_1,ldots,q_minR${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img522.gif">'; 
$key = q/{_inline}$I(g_i)=1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img533.gif">'; 
$key = q/{_inline}$f(x)inR[x]LeftrightarrowI(f)inR${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img456.gif">'; 
$key = q/{_inline}$R_i^*${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img209.gif">'; 
$key = q/{_inline}$papproxp_i${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img356.gif">'; 
$key = q/{_inline}$b=q_1cdotsq_sin(q_j)=(p)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img361.gif">'; 
$key = q/{_inline}$c_jinI_j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img231.gif">'; 
$key = q/{_inline}$pmn${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img157.gif">'; 
$key = q/{_inline}$R[x,y]=(R[x])[y]=(R[y])[x]${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img52.gif">'; 
$key = q/{_inline}$bZ+bZx${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img624.gif">'; 
$key = q/{_inline}$1_R=(1_R_1,1_R_2,ldots,1_R_n)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img206.gif">'; 
$key = q/{_inline}$(m,n)=1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img217.gif">'; 
$key = q/{_inline}$(1)=bZ${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img159.gif">'; 
$key = q/{eg}enumerateitem有理整数環_inline$bZ$_inlineは、整域である。item有理数体_inline$bQ$_inline、実数体_inline$bR$_inline、複素数体_inline$bC$_inlineは、いずれも可換体である。item_inline$R$_inlineを環とするとき、_inline$R$_inline上の全行列環、_inline$mat_n(R)$_inlineは、非可換な環である。item_inline$n$_inlineを自然数としたとき、_inline$bZ_n=bZnbZ={bar0,bar1,ldots,overlinen-1}$_inlineに、通常の和、積の_inline$n$_inlineによる剰余によって演算を定義すると、元の数が_inline$n$_inlineである可換環になる。enumerate{eg}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img11.gif">'; 
$key = q/{_inline}$asnotinP'${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img312.gif">'; 
$key = q/{_inline}$phi_S:RtoS^-1R;(amapstoa1)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img263.gif">'; 
$key = q/{_inline}$c_0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img190.gif">'; 
$key = q/{_inline}$Rkerf${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img105.gif">'; 
$key = q/{_inline}$f(x)g(x)=I(f)I(g)f_0(x)g_0(x)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img473.gif">'; 
$key = q/{_inline}$I_i${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img602.gif">'; 
$key = q/{displaymath}c_0equivc_1equivcdotsequivc_i-1equiv0notequivc_i;(modp).{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img195.gif">'; 
$key = q/{_inline}$a_1,a_2,ldots,a_n${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img423.gif">'; 
$key = q/{_inline}$degg_0=degg=0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img490.gif">'; 
$key = q/{_inline}$NneqN_0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img579.gif">'; 
$key = q/{displaymath}emptysetneq{rho(x)mid0neqxinI}subsetX{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img90.gif">'; 
$key = q/{_inline}$bQ${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img204.gif">'; 
$key = q/{_inline}$x_i${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img243.gif">'; 
$key = q/{_inline}$0neqa_i,b_jinR${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img429.gif">'; 
$key = q/{_inline}$gneq0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img45.gif">'; 
$key = q/{_inline}$a_0,a_1,ldots,a_n${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img430.gif">'; 
$key = q/{_inline}$aapproxp${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img345.gif">'; 
$key = q/{_inline}$RaneqR${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img276.gif">'; 
$key = q/{displaymath}(a+I)+(b+I)=(a+b)+I,;(a+I)cdot(b+I)=(ab)+I{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img65.gif">'; 
$key = q/{_inline}$f:MtoM'${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img543.gif">'; 
$key = q/{_inline}$a_i_1,ldots,a_i_s_i${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img601.gif">'; 
$key = q/{_inline}$subset${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img311.gif">'; 
$key = q/{_inline}$(a_1)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img379.gif">'; 
$key = q/{displaymath}f(x)=g(x)h(x),;r=degg;SPM_gt;0,;s=degh;SPM_gt;0,{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img185.gif">'; 
$key = q/{displaymath}barf((a+kerf)(b+kerf))=barf(ab+kerf)=f(ab)=f(a)f(b)=barf(a+kerf)barf(b+kerf){displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img108.gif">'; 
$key = q/{_inline}$c=ba${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img441.gif">'; 
$key = q/{ex}以下を示せ。enumerateitem環_inline$R$_inlineの左（右、両側）イデアル_inline$I,J$_inlineに対して、_inline$IcapJ$_inline、_inline$I+J$_inlineは共に、左（右、両側）イデアルである。item_inline$I,J$_inlineが環_inline$R$_inlineの両側イデアルならば、_inline$IJ$_inlineも両側イデアルで、_inline$IJsubsetIcapJ$_inlineを満たす。また、等号が成り立たない例をあげよ。enumerate{ex}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img62.gif">'; 
$key = q/{_inline}$(a_i)=(a_i+1)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img390.gif">'; 
$key = q/{_inline}$N=N_0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img584.gif">'; 
$key = q/{_inline}$g(x)=b_0+b_1x+cdots+b_mx^m${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img461.gif">'; 
$key = q/{_inline}$p_iapproxq_i${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img405.gif">'; 
$key = q/{displaymath}I+J=RLeftrightarrowx+y=1mboxとなるxinI,;yinJmboxが存在する。{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img210.gif">'; 
$key = q/{_inline}$x^n-2${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img201.gif">'; 
$key = q/{_inline}$cinR${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img137.gif">'; 
$key = q/{_inline}$K[x]${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img180.gif">'; 
$key = q/{_inline}$a,binR${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img328.gif">'; 
$key = q/{displaymath}f=gq+r=gq'+r',;degr,degr';SPM_lt;degg{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img42.gif">'; 
$key = q/{_inline}$(a)subset(p)=(ab)subset(a)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img344.gif">'; 
$key = q/{_inline}$R[x_1,ldots,x_n-1,x_n]=(R[x_1,ldots,x_n-1])[x_n]${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img504.gif">'; 
$key = q/{displaymath}r=r(u^-1u)=(ru^-1)uinRIsubsetI.{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img75.gif">'; 
$key = q/{_inline}$a,binbZ${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img216.gif">'; 
$key = q/{_inline}$(rt)(as)=artsinP'${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img294.gif">'; 
$key = q/{displaymath}f=g(q_1+(a_nb_m^-1)x^n-m)+r{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img40.gif">'; 
$key = q/{displaymath}x_iequiv1;(modI_i),;jneqimboxの時はx_iequiv0;(modI_j).{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img226.gif">'; 
$key = q/{_inline}$cmida_i${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img413.gif">'; 
$key = q/{_inline}$(a)neqR${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img372.gif">'; 
$key = q/{displaymath}I=RLeftrightarrowU(R)capIneqemptyset.{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img70.gif">'; 
$key = q/{_inline}$ainI-{0}${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img79.gif">'; 
$key = q/{_inline}$RI${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img119.gif">'; 
$key = q/{_inline}$rho(a)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img91.gif">'; 
$key = q/{_inline}$rgeqm${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img610.gif">'; 
$key = q/{eg}_inline$I$_inlineを、環_inline$R$_inlineの両側イデアルで、_inline$(RneqI)$_inlineとするとき、displaymathf:RlongrightarrowRI,;(amapstoa+I)displaymathは、環準同型で、全射である。{eg}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img100.gif">'; 
$key = q/{_inline}$f(x)=0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img21.gif">'; 
$key = q/{_inline}$a=p_1p_2cdotsp_r=q_1q_2cdotsq_s${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img394.gif">'; 
$key = q/{_inline}$supset${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img316.gif">'; 
$key = q/{_inline}$g(x),h(x)inK[x]${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img483.gif">'; 
$key = q/{_inline}$c_s${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img192.gif">'; 
$key = q/{_inline}$I_1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img236.gif">'; 
$key = q/{_inline}$uinU(R)capI${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img73.gif">'; 
$key = q/{_inline}$bneq0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img85.gif">'; 
$key = q/{_inline}$as${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img251.gif">'; 
$key = q/{_inline}$c=v_1cdotsv_t${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img354.gif">'; 
$key = q/{_inline}$(n)subset(m)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img149.gif">'; 
$key = q/{_inline}$j_0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img466.gif">'; 
$key = q/{_inline}$11notinP'${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img318.gif">'; 
$key = q/{_inline}$imfneq0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img562.gif">'; 
$key = q/{_inline}$t'notinP${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img324.gif">'; 
$key = q/{_inline}$uinU(R)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img402.gif">'; 
$key = q/{_inline}$degf=-infty${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img25.gif">'; 
$key = q/{_inline}$at+bsinP${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img290.gif">'; 
$key = q/{_inline}$f(x)=g(x)h(x)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img171.gif">'; 
$key = q/{_inline}$A=bC[G]${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img550.gif">'; 
$key = q/{_inline}$xequiva_2;(modI_2)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img224.gif">'; 
$key = q/{_inline}$a_m=sum_j=1^s_m-ec_ja_(m-e)_j${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img612.gif">'; 
$key = q/{_inline}$(m)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img212.gif">'; 
$key = q/{displaymath}(n)mbox：極大イデアルLeftrightarrownmboxは素数{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img160.gif">'; 
$key = q/{_inline}$asinU(R_P)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img315.gif">'; 
$key = q/{_inline}$asinP'${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img300.gif">'; 
$key = q/{_inline}$r=r'${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img49.gif">'; 
$key = q/{_inline}$b_m${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img33.gif">'; 
$key = q/{_inline}$U(R[x])=U(R)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img494.gif">'; 
$key = q/{_inline}$(as'-a's)t=0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img306.gif">'; 
$key = q/{_inline}$a'bf_0(x)=ab'f'_0(x)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img445.gif">'; 
$key = q/{_inline}$xf(x)=a_ix^i+1+cdots+a_1x^2+a_0xinI${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img597.gif">'; 
$key = q/{_inline}$finsum_i=0^rsum_j=1^s_iR[x]f_i_j(x)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img614.gif">'; 
$key = q/{_inline}$r'-r=0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img47.gif">'; 
$key = q/{_inline}$-(as)=(-a)s${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img259.gif">'; 
$key = q/{_inline}$e_0,e_1,ldots,e_n${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img434.gif">'; 
$key = q/{displaymath}barf:Rkerfrightarrowimf,;(a+kerfmapstof(a)){displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img107.gif">'; 
$key = q/{displaymath}(x+I)(y+I)subsetxy+I{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img56.gif">'; 
$key = q/{_inline}$MsubsetR-U(R)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img274.gif">'; 
$key = q/{_inline}$(i),(ii)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img495.gif">'; 
$key = q/{_inline}$a_1notinU(R)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img381.gif">'; 
$key = q/{_inline}$q_1,r${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img37.gif">'; 
$key = q/{_inline}$f_0(x),g_0(x)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img486.gif">'; 
$key = q/{_inline}$q=q'${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img48.gif">'; 
$key = q/{_inline}$(q)=R${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img367.gif">'; 
$key = q/{_inline}$a_1=p_2a_2${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img383.gif">'; 
$key = q/{_inline}$kerf${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img557.gif">'; 
$key = q/{_inline}$(f(x))${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img177.gif">'; 
$key = q/{_inline}$(p)=(q)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img368.gif">'; 
$key = q/{_inline}$(n)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img213.gif">'; 
$key = q/{_inline}$f(x)=a_0+a_1x+cdots+a_nx^ninR[x]${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img425.gif">'; 
$key = q/{_inline}$phi(g)inGL(V)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img553.gif">'; 
$key = q/{_inline}$a=p_1cdotsp_rin(p_i)=(p)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img359.gif">'; 
$key = q/{_inline}$(a_1s_1)+(a_2s_2)=(a_1s_2+a_2s_1)s_1s_2${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img254.gif">'; 
$key = q/{_inline}$K=cQ(R)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img409.gif">'; 
$key = q/{_inline}$0neqainR-U(R)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img371.gif">'; 
$key = q/{_inline}$JsubsetI${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img284.gif">'; 
$key = q/{_inline}$f(x)mboxが原始多項式LeftrightarrowI(f)approx1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img457.gif">'; 
$key = q/{_inline}$x_1inR${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img238.gif">'; 
$key = q/{_inline}$b_0c_0,b_1c_1,ldots,b_nc_n${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img432.gif">'; 
$key = q/{_inline}$p^2${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img188.gif">'; 
$key = q/{_inline}$jgeq2${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img227.gif">'; 
$key = q/{_inline}$(2)Rightarrow(1)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img364.gif">'; 
$key = q/{_inline}$RtimesS${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img248.gif">'; 
$key = q/{_inline}$p_ra_r${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img392.gif">'; 
$key = q/{_inline}$kerf=0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img563.gif">'; 
$key = q/{_inline}$R-U(R)subsetM${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img278.gif">'; 
$key = q/{_inline}$bin(p)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img342.gif">'; 
$key = q/{_inline}$bQ[x_1,cdots,x_n]${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img407.gif">'; 
$key = q/{_inline}$1inIcapU(R)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img71.gif">'; 
$key = q/{_inline}$(p_1)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img397.gif">'; 
$key = q/{_inline}$f_1cdotsf_l${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img524.gif">'; 
$key = q/{_inline}$1=c_1+c_2${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img219.gif">'; 
$key = q/{_inline}$c_1^(j)+c_j=1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img229.gif">'; 
$key = q/{_inline}$U(R)capIneqemptyset${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img72.gif">'; 
$key = q/{_inline}$(g(x))${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img178.gif">'; 
$key = q/{_inline}$phi:GtoGL(V),;(gmapstophi(g))${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img554.gif">'; 
$key = q/{_inline}$ainRa${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img83.gif">'; 
$key = q/{_inline}$(n)=(1)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img156.gif">'; 
$key = q/{_inline}$R[x_1,ldots,x_n]=(R[x_1,ldots,x_n-1])[x_n]${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img50.gif">'; 
$key = q/{_inline}$dinR${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img144.gif">'; 
$key = q/{_inline}$c'=b'a'${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img442.gif">'; 
$key = q/{displaymath}(a,s)sim(a',s')Leftrightarrow(as'-a's)t=0mboxとなるtinSmboxが存在する。{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img249.gif">'; 
$key = q/{_inline}$f=f(x)=a_0+a_1x+cdots+a_nx^ninR[x],;a_nneq0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img19.gif">'; 
$key = q/{_inline}$f(x)=a_0+a_1x+cdots+a_lx^l${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img460.gif">'; 
$key = q/{_inline}$m=pmn${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img152.gif">'; 
$key = q/{_inline}$p_1notinU(R)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img378.gif">'; 
$key = q/{_inline}$p_2${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img382.gif">'; 
$key = q/{_inline}$(a)subset(b)Leftrightarrowa=bc${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img329.gif">'; 
$key = q/{_inline}$U(R)subsetR-{0}${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img5.gif">'; 
$key = q/{_inline}$(as)(bt)=11${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img321.gif">'; 
$key = q/{_inline}$a'inP${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img304.gif">'; 
$key = q/{_inline}$ainU(R)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img80.gif">'; 
$key = q/{_inline}$R-{0}${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img6.gif">'; 
$key = q/{_inline}$I(g)I(h)approxI(gh)inR${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img489.gif">'; 
$key = q/{_inline}$R_P${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img287.gif">'; 
$key = q/{_inline}$degh;SPM_lt;n${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img35.gif">'; 
$key = q/{_inline}$MneqR${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img272.gif">'; 
$key = q/{_inline}$(p)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img369.gif">'; 
$key = q/{_inline}$f_0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img517.gif">'; 
$key = q/{_inline}$degf=0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img508.gif">'; 
$key = q/{_inline}$a_imidl${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img417.gif">'; 
$key = q/{_inline}$(2)Leftrightarrow(3)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img363.gif">'; 
$key = q/{_inline}$0_R=(0_R_1,0_R_2,ldots,0_R_n)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img207.gif">'; 
$key = q/{_inline}$(p)subsetI=(q)subsetR${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img366.gif">'; 
$key = q/{_inline}$sim${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img2.gif">'; 
$key = q/{_inline}$b'${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img444.gif">'; 
$key = q/{_inline}$pm1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img158.gif">'; 
$key = q/{_inline}$I_1+I_j=R${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img228.gif">'; 
$key = q/{_inline}$ain(p)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img341.gif">'; 
$key = q/{_inline}$(i)Rightarrow(ii)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img577.gif">'; 
$key = q/{_inline}$cinI=(a)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img143.gif">'; 
$key = q/{_inline}$(a,s)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img250.gif">'; 
$key = q/{_inline}$phi_S${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img264.gif">'; 
$key = q/{_inline}$degf;SPM_gt;0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img511.gif">'; 
$key = q/{_inline}$x=a_1c_2+a_2c_1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img221.gif">'; 
$key = q/{_inline}$bigcup_i=1^infty(a_i)=(d)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img388.gif">'; 
$key = q/{_inline}$I=(a)neq(0)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img134.gif">'; 
$key = q/{_inline}$a=p_1p_2a_2${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img384.gif">'; 
$key = q/{_inline}$M_1subsetM_2subsetcdotssubsetM_i${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img573.gif">'; 
$key = q/{_inline}$RNsubsetN${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img542.gif">'; 
$key = q/{_inline}$J=(b)subset(a)=I${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img142.gif">'; 
$key = q/{_inline}$ngeqm${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img31.gif">'; 
$key = q/{_inline}$g(q-q')=r'-r${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img43.gif">'; 
$key = q/{_inline}$abt'=stt'${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img325.gif">'; 
$key = q/{displaymath}(f_1(x))=(f_2(x))Leftrightarrowf_1(x)=cf_2(x);(cinK^*).{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img176.gif">'; 
$key = q/{_inline}$R_P-P'=U(R_P)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img327.gif">'; 
$key = q/{_inline}$degh(x);SPM_gt;1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img173.gif">'; 
$key = q/{_inline}$1-c_2cdotsc_n=c_1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img233.gif">'; 
$key = q/{_inline}$i=1,2,ldots,n${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img420.gif">'; 
$key = q/{_inline}$ainI${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img92.gif">'; 
$key = q/{_inline}$ainR-U(R)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img275.gif">'; 
$key = q/{_inline}$I_0,I_1,ldots,I_r${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img600.gif">'; 
$key = q/{_inline}$q_iin(p_1)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img398.gif">'; 
$key = q/{_inline}$mmidn${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img150.gif">'; 
$key = q/{_inline}$b=q_1cdotsq_s${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img353.gif">'; 
$key = q/{_inline}$IsubsetM${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img269.gif">'; 
$key = q/{_inline}$n=degf${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img32.gif">'; 
$key = q/{_inline}$Rx+N_0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img581.gif">'; 
$key = q/{displaymath}barf(1_Rskerf)=barf(1+kerf)=f(1_R)=1_R'.{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img109.gif">'; 
$key = q/{_inline}$degf${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img507.gif">'; 
$key = q/{_inline}$capproxc'${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img454.gif">'; 
$key = q/{_inline}$n=i;SPM_lt;s=degh${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img197.gif">'; 
$key = q/{eg}_inline$x^2+1$_inline、_inline$x^2-2$_inlineが_inline$bQ$_inline上既約であることは簡単に確かめられるから、_inline$(x^2+1)$_inline、_inline$(x^2-2)$_inlineは、_inline$bQ[x]$_inlineの極大イデアルであり、従って、_inline$bQ[sqrt-1]simeqbQ[x](x^2+1)$_inline、_inline$bQ[sqrt2]simeqbQ[x](x^2-2)$_inlineは、体であることが分かる。{eg}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img183.gif">'; 
$key = q/{_inline}$g_i${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img535.gif">'; 
$key = q/{displaymath}degg+deg(q-q')=deg(g(q-q'))=deg(r'-r)leqmax(degr',degr);SPM_lt;degg.{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img44.gif">'; 
$key = q/{displaymath}f(x)=a_0+a_1x+cdots+a_nx^n,;a_iinRmboxfori=0,1,ldots,n{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img13.gif">'; 
$key = q/{_inline}$q_1q_2cdotsq_s=ain(p_1)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img396.gif">'; 
$key = q/{_inline}$s'notinP${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img305.gif">'; 
$key = q/{_inline}$a_nneq0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img29.gif">'; 
$key = q/{_inline}$M_1subsetM_2subsetcdots${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img569.gif">'; 
$key = q/{_inline}$g_0(x)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img472.gif">'; 
$key = q/{_inline}$phi:GtoGL(V)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img555.gif">'; 
$key = q/{displaymath}sum_i_1,ldots,i_na_i_1,ldots,i_nx_1^i_1cdotsx_n^i_n,;a_i_1,ldots,i_ninR.{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img51.gif">'; 
$key = q/{_inline}$f=p_1cdotsp_kf_1cdotsf_l=q_1cdotsq_mg_1cdotsg_n${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img521.gif">'; 
$key = q/{_inline}$x^3-3x^2-9x-6${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img202.gif">'; 
$key = q/{_inline}$a_0=b_0c_0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img187.gif">'; 
$key = q/{_inline}$g_1cdotsg_n${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img525.gif">'; 
$key = q/{_inline}$f=a_nx^n+cdots+a_1x+a_0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img28.gif">'; 
$key = q/{_inline}$binRa${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img97.gif">'; 
$key = q/{_inline}$r=b-aqinI${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img96.gif">'; 
$key = q/{_inline}$a_r${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img391.gif">'; 
$key = q/{eg}enumerateitem_inline$S$_inlineを_inline$R$_inlineの非零因子全体の時、_inline$S^-1R$_inlineを_inline$R$_inlineの全商環(ringoftotalquotients)という。item_inline$R$_inlineが整域のときは、_inline$R$_inlineの全商環は体になる。これを商体(quotientfield)と呼び、_inline$cQ(R)$_inlineとかく。enumerateitem_inline$cQ(bZ)=bQ$_inline、有理整数環の商体は、有理数体である。item_inline$cQ(K[x_1,ldots,x_n])=K(x_1,ldots,x_n)={fgmidf,ginK[x_1,ldotsx_n],;gneq0}$_inlineであり、これを有理関数体という。item_inline$P$_inlineを可換環_inline$R$_inlineの素イデアル、_inline$(R-p)^-1R$_inlineを_inline$R_P$_inlineと書き、_inline$R$_inlineの_inline$P$_inlineによる局所化(localization)と呼ぶ。enumerateenumerate{eg}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img266.gif">'; 
$key = q/{_inline}$c_iinK${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img532.gif">'; 
$key = q/{_inline}$(a)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img68.gif">'; 
$key = q/{_inline}$xinN-N_0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img580.gif">'; 
$key = q/{displaymath}f(a+b)=f(a)+f(b),;f(ra)=rf(a),;(rinR,;a,binM){displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img544.gif">'; 
$key = q/{_inline}$(1)Rightarrow(3)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img365.gif">'; 
$key = q/{_inline}$(ii)Rightarrow(i)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img585.gif">'; 
$key = q/{_inline}$aapproxb${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img334.gif">'; 
$key = q/{_inline}$0x=x0=0;(neq1)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img4.gif">'; 
$key = q/{_inline}$I(f)I(g)approxI(fg)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img476.gif">'; 
$key = q/{_inline}$m=degf${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img608.gif">'; 
$key = q/{_inline}$q_iapproxp_1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img400.gif">'; 
$key = q/{_inline}$c_iinR${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img534.gif">'; 
$key = q/{displaymath}I(f)approxp_1cdotsp_kapproxq_1cdotsq_m{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img526.gif">'; 
$key = q/{_inline}$c=ba=(b'a')u=c'u${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img450.gif">'; 
$key = q/{_inline}$I_2cdotsI_n${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img237.gif">'; 
$key = q/{_inline}$b=uinU(R)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img348.gif">'; 
$key = q/{_inline}$h(x)=I(h)h_0(x)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img485.gif">'; 
$key = q/{displaymath}NsubsetM_msubsetM_m+1subsetcdotssubsetN.{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img591.gif">'; 
$key = q/{_inline}$a(b-u)=p-p=0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img347.gif">'; 
$key = q/{_inline}$degf(x)geq1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img166.gif">'; 
$key = q/{_inline}$R=(1)subset(b)=J${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img147.gif">'; 
$key = q/{_inline}$a,binP,;s,tnotinP${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img289.gif">'; 
$key = q/{_inline}$rxinN${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img539.gif">'; 
$key = q/{eg}enumerateitem加群は、_inline$bZ$_inline-加群である。item環_inline$R$_inlineは、_inline$R$_inline-加群であり、_inline$I$_inlineが_inline$R$_inline-加群_inline$R$_inlineの部分加群であることと、_inline$I$_inlineが_inline$R$_inlineの左イデアルであることは同値である。item_inline$K$_inlineを体としたとき、_inline$K$_inline-加群は、_inline$K$_inline-ベクトル空間の事である。enumerate{eg}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img546.gif">'; 
$key = q/{_inline}${M_imidiinbN}${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img570.gif">'; 
$key = q/{displaymath}c=c1=c(ba)=(cb)a=1a=a{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img86.gif">'; 
$key = q/{_inline}$c_1inI_1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img234.gif">'; 
$key = q/{_inline}$bZ${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img203.gif">'; 
$key = q/{displaymath}I_i={rinRmidf(x)=a_ix^i+cdots+a_1x+a_0inImboxでa_i=rmboxとなるものがる。}{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img595.gif">'; 
$key = q/{_inline}$f_0(x)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img439.gif">'; 
$key = q/{_inline}$(ii)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img518.gif">'; 
$key = q/{_inline}$q_1=p_1u${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img401.gif">'; 
$key = q/{displaymath}x_1equiv1;(modI_1),;x_1equiv0;(modI_2cdotsI_n){displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img239.gif">'; 
$key = q/{_inline}$M_n${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img571.gif">'; 
$key = q/{_inline}$N=;SPM_lt;u_1,u_2,ldots,u_n;SPM_gt;${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img588.gif">'; 
$key = q/{_inline}$I_r=I_r+1=cdots${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img599.gif">'; 
$key = q/{_inline}$ainP${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img299.gif">'; 
$key = q/{_inline}$(m)=(n)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img151.gif">'; 
$key = q/{_inline}$f(ra)=rf(a)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img545.gif">'; 
$key = q/{_inline}$b_0${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img189.gif">'; 
$key = q/{_inline}$degh;SPM_lt;degf${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img514.gif">'; 
$key = q/{_inline}$R=I_1+I_2cdotsI_n${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img235.gif">'; 
$key = q/{_inline}$asinU(R_P)capP'${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img319.gif">'; 
$key = q/{_inline}$p_1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img375.gif">'; 
$key = q/{_inline}$g(x)=I(g)g_0(x)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img484.gif">'; 
$key = q/{_inline}$c'=cu${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img452.gif">'; 
$key = q/{_inline}$bZ_n=bZ(n)${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img162.gif">'; 
$key = q/{_inline}$bmida${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img331.gif">'; 
$key = q/{_inline}$c_1^(j)inI_1${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img230.gif">'; 
$key = q/{_inline}$JcapU(R)=emptyset${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img283.gif">'; 
$key = q/{_inline}$Leftarrow${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img301.gif">'; 
$key = q/{_inline}$x_iinR${_inline}/;
$cached_env_img{$key} ='<IMG  ALIGN=MIDDLE ALT="" SRC="img225.gif">'; 

1;

